package com.example.maja.myapplication.backend.events;

/**
 * Created by Maja on 29.8.2017.
 */

public enum EventType {
    ERROR_EVENT,
    LOGIN_EVENT,
    CREATE_ACCOUNT_EVENT,
    GET_ALL_NEWS_EVENT,
    ADD_NEWS_EVENT,
    UPDATE_NEWS_EVENT,
    DELTE_NEWS_EVENT,
    GET_DOG_LIST_EVENT,
    GET_SHELTER_BY_ID_EVENT,
    GET_SHELTER_LIST_EVENT,
    ADD_SHELTER_EVENT,
    ADD_DOG_EVENT,
    UPDATE_SHELTER_EVENT,
    DELETE_SHELTER_EVENT,
    UPDATE_DOG_EVENT,
    UPDATE_USER_EVENT,
    DELETE_DOG_EVENT,
    GET_USER_BY_ID_EVENT,
    GET_FAVORITE_DOG_EVENT
}
